language: php

cache:
  directories:
    - $HOME/.composer/cache

branches:
  except:
    - /^analysis-.*$/
    - /^patch-.*$/

php:
    - 7.2
    - 7.4
    - 8.0

env:
  global:
    - TEST_COMMAND="composer test"
  matrix:
    - SYMFONY_VERSION=4.4.*
    - SYMFONY_VERSION=5.2.*

matrix:
  fast_finish: true
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true TEST_COMMAND="composer test-ci" SYMFONY_VERSION=4.4.*
    - php: 7.4
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true TEST_COMMAND="composer test-ci" SYMFONY_VERSION=5.2.*
    - php: 8.0
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" COVERAGE=true TEST_COMMAND="composer test-ci" SYMFONY_VERSION=5.2.*
    - php: hhvm
      dist: trusty
      env: SYMFONY_VERSION=4.4.*
  allow_failures:
    - php: hhvm
      dist: trusty
      env: SYMFONY_VERSION=4.4.*

install:
    - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
    - travis_retry composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
    - $TEST_COMMAND

after_success:
    - if [[ $COVERAGE = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [[ $COVERAGE = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
